# Generated by Django 4.1.6 on 2023-02-26 17:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_services_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.TextField(max_length=140)),
                ('phonenumber', models.TextField(max_length=15)),
                ('servicetype', models.TextField(max_length=100)),
                ('datetime', models.DateTimeField(verbose_name=datetime.datetime(2023, 2, 26, 17, 8, 31, 748759, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
