# Generated by Django 4.1.6 on 2023-02-26 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_appointment_datetime_alter_appointment_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
