# Generated by Django 4.1.6 on 2023-02-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='phonenumber',
            field=models.CharField(max_length=15),
        ),
    ]
