# Generated by Django 4.1.6 on 2023-02-26 17:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_appointment_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='date',
            field=models.DateField(null=True, verbose_name=datetime.datetime(2023, 2, 26, 17, 26, 10, 903959, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='servicetype',
            field=models.CharField(max_length=100),
        ),
    ]
