# Generated by Django 4.1.6 on 2023-02-26 17:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_appointment_date_alter_appointment_servicetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(null=True, verbose_name=datetime.datetime(2023, 2, 26, 17, 27, 16, 300407, tzinfo=datetime.timezone.utc)),
        ),
    ]
