# Generated by Django 4.1.6 on 2023-02-26 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_appointment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='date',
        ),
    ]
